window.DEFAULT_PRODUCTS = [
  {
    id: "su-1",
    name: "Shukra Udgam",
    tagline: "The Rise of Attraction",
    description:
      "A commanding blend built for presence — deep royal notes wrapped in our signature sandalwood-amber-musk base, designed to draw the room toward you.",
    price: 1499,
    sale_price: 1199,
    image: "assets/shukra.jpg",
    featured: true,
    stock: 20,
    category: "Power",
    glyph: "♛",
    energy: "Dominance · Power · Attraction",
    notes: {
      top: "Bergamot, Pink Pepper",
      heart: "Saffron, Iris",
      base: "Sandalwood, Amber, White Musk",
    },
    concentration: "18–20% Extrait de Parfum",
    longevity: "8–10 hours",
    size: "50ml / 100ml",
    family: "Floral Amber",
    occasion:
      "Evening gatherings, celebrations, moments that call for quiet presence",
    ritual:
      "Apply to pulse points — wrists, neck, behind the ears — before meetings or moments requiring presence.",
  },
  {
    id: "ms-1",
    name: "Mann Shanti",
    tagline: "Stillness of the Mind",
    description:
      "A crystalline, calming composition for clarity and inner peace — soft sky-blue notes settling over our warm signature base.",
    price: 1499,
    sale_price: 1199,
    image: "assets/mann.jpg",
    featured: true,
    stock: 20,
    category: "Calm",
    glyph: "☯",
    energy: "Peace · Clarity · Inner Calm",
    notes: {
      top: "Lavender, Mint",
      heart: "White Lotus, Violet",
      base: "Sandalwood, Amber, White Musk",
    },
    concentration: "18–20% Extrait de Parfum",
    longevity: "7–9 hours",
    size: "50ml / 100ml",
    family: "Crystal Musk",
    occasion: "Meditation, quiet mornings, deep focus work",
    ritual:
      "Mist lightly before meditation or breathwork to anchor a calm, focused state.",
  },
  {
    id: "st-1",
    name: "Surya Tej",
    tagline: "Radiance of the Sun",
    description:
      "A golden, radiant amber fragrance for warmth and quiet royalty — the scent of standing fully in your own light.",
    price: 1499,
    sale_price: 1199,
    image: "assets/surya.jpg",
    featured: true,
    stock: 20,
    category: "Warmth",
    glyph: "☀",
    energy: "Warmth · Royalty · Authority",
    notes: {
      top: "Blood Orange, Cardamom",
      heart: "Golden Amber, Cinnamon",
      base: "Sandalwood, Amber, White Musk",
    },
    concentration: "18–20% Extrait de Parfum",
    longevity: "8–10 hours",
    size: "50ml / 100ml",
    family: "Golden Amber",
    occasion: "Milestones, mornings, moments that call for confidence",
    ritual:
      "Apply at sunrise to set an intention of confidence and radiance for the day ahead.",
  },
  {
    id: "as-1",
    name: "Aura Shuddhi",
    tagline: "Purity of the Aura",
    description:
      "A soft, lavender-violet blend for charm and harmony — an aura-clearing fragrance for gentle magnetism.",
    price: 1499,
    sale_price: 1199,
    image: "assets/aura.jpg",
    featured: false,
    stock: 20,
    category: "Charm",
    glyph: "✿",
    energy: "Charm · Magnetism · Harmony",
    notes: {
      top: "Violet Leaf, Litchi",
      heart: "Lavender, Jasmine",
      base: "Sandalwood, Amber, White Musk",
    },
    concentration: "18–20% Extrait de Parfum",
    longevity: "7–9 hours",
    size: "50ml / 100ml",
    family: "Soft Floral Woods",
    occasion:
      "Gatherings, difficult conversations, moments that call for harmony",
    ritual:
      "Wear before gatherings or difficult conversations to soften energy and invite harmony.",
  },
  {
    id: "kc-1",
    name: "Kismat Connection",
    tagline: "Threads of Destiny",
    description:
      "A smoked-obsidian oud composition for mystery and depth — worn by those who trust the pull of alignment.",
    price: 1599,
    sale_price: 1299,
    image: "assets/kismat.jpg",
    featured: true,
    stock: 20,
    category: "Mystery",
    glyph: "☾",
    energy: "Mystery · Depth · Alignment",
    notes: {
      top: "Black Pepper, Smoke Accord",
      heart: "Oud, Rose",
      base: "Sandalwood, Amber, White Musk",
    },
    concentration: "18–20% Extrait de Parfum",
    longevity: "9–11 hours",
    size: "50ml / 100ml",
    family: "Smoked Oud",
    occasion: "Reflection, alignment, nights of introspection",
    ritual:
      "Apply before sleep or reflection to support introspection and trust in your own timing.",
  },
];
